[package]
name = "benchmark_data"
description = "Continuous benchmarking infrastructure for Tremor"
version = "0.1.0"
authors = ["Akshat Agarwal <humancalico@disroot.org>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/humancalico/tremor-benchmark"
keywords = ["tremor", "benchmark"]
categories = ["Benchmarking"]

[dependencies]
color-eyre = "0.5.10"
clap = "3.0.0-beta.2"
