name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.profile }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            kind: test
          - os: windows-latest
            kind: test
          - os: ubuntu-latest
            kind: test
          - os: ubuntu-latest
            kind: lint

    env:
      RUST_BACKTRACE: full
      RUSTFLAGS: -D warnings
      CARGO_TERM_COLOR: always

    steps:
      - name: clone repository
        uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: check clippy
        if: matrix.kind == 'lint'
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: check rustfmt
        if: matrix.kind == 'lint'
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
