name: deploy to github pages

# TODO only run this when website/ or data/ is changed
on: [ push, pull_request ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2

      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # TODO cache to reduce installation time
      # See https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time

      - uses: pnpm/action-setup@v2.0.1
        working-directory: ./website
        with:
          version: 6.0.2
          run_install: true
        run: |
          pnpm install
          pnpm run build
          pnpm run export

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./website/out
